name: Shuttle Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: "./"
          name: "attendance-manager"
          allow-dirty: "true"
          no-test: "true"
          cargo-shuttle-version: "0.43.0"
          secrets: |
            LINE_CHANNEL_SECRET = '${{ secrets.LINE_CHANNEL_SECRET }}'
            LINE_CHANNEL_ACCESS_TOKEN = '${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}'
